spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

api:
  version: 1.0.0
  title: Cornershopp Users Service
  basePackage: com.cornershopapp.users-api
  description: Automated JSON API documentation for API's built with Spring
  terms: https://cornershopapp.com/

#spring.datasource.url=jdbc:mysql://localhost:3306/users?serverTimezone=UTC
#spring.datasource.username=user
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.generate-ddl=false
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#api.version: 1.0.0
#api.title: Cornershopp Users Service
#api.basePackage: com.cornershopapp.users-api
#api.description: Automated JSON API documentation for API's built with Spring
#api.terms: https://cornershopapp.com/