package com.cornershopapp.usersapi.repository;

import com.cornershopapp.usersapi.domain.models.User;
import java.util.Optional;
import java.util.UUID;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface UsersRepository extends CrudRepository<User, Long> {
    // All these methods are never implemented by us but generated by Hibernate
    boolean existsByEmail(String email);
    Optional<User> findByUuid(UUID uuid);
    Optional<User> findByEmail(String email);
    /*
        We can even use logical operators to combine conditions and these will be translated to conditions in the
        where section of the generated query. In this case the query will be something like:
        select * from users where email = :email and uuid = :uuid limit 1

        We should define indexes for this combined columns in the User entity, generate the SQL and the migration
     */
    Optional<User> findByEmailAndUuid(String email, UUID uuid);
}
